//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Index.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoUnitario {
            get {
                return this.CostoUnitarioField;
            }
            set {
                if ((this.CostoUnitarioField.Equals(value) != true)) {
                    this.CostoUnitarioField = value;
                    this.RaisePropertyChanged("CostoUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoda {
            get {
                return this.IdSodaField;
            }
            set {
                if ((this.IdSodaField.Equals(value) != true)) {
                    this.IdSodaField = value;
                    this.RaisePropertyChanged("IdSoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContProd", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class ContProd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContenido {
            get {
                return this.IdContenidoField;
            }
            set {
                if ((this.IdContenidoField.Equals(value) != true)) {
                    this.IdContenidoField = value;
                    this.RaisePropertyChanged("IdContenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soda", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class Soda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Horario_apField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Horario_ciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario_ap {
            get {
                return this.Horario_apField;
            }
            set {
                if ((object.ReferenceEquals(this.Horario_apField, value) != true)) {
                    this.Horario_apField = value;
                    this.RaisePropertyChanged("Horario_ap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario_ci {
            get {
                return this.Horario_ciField;
            }
            set {
                if ((object.ReferenceEquals(this.Horario_ciField, value) != true)) {
                    this.Horario_ciField = value;
                    this.RaisePropertyChanged("Horario_ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoda {
            get {
                return this.IdSodaField;
            }
            set {
                if ((this.IdSodaField.Equals(value) != true)) {
                    this.IdSodaField = value;
                    this.RaisePropertyChanged("IdSoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacion {
            get {
                return this.LocalizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacionField, value) != true)) {
                    this.LocalizacionField = value;
                    this.RaisePropertyChanged("Localizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCarrito {
            get {
                return this.IdCarritoField;
            }
            set {
                if ((this.IdCarritoField.Equals(value) != true)) {
                    this.IdCarritoField = value;
                    this.RaisePropertyChanged("IdCarrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacion {
            get {
                return this.LocalizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacionField, value) != true)) {
                    this.LocalizacionField = value;
                    this.RaisePropertyChanged("Localizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrador", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class Administrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoda {
            get {
                return this.IdSodaField;
            }
            set {
                if ((this.IdSodaField.Equals(value) != true)) {
                    this.IdSodaField = value;
                    this.RaisePropertyChanged("IdSoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacion {
            get {
                return this.LocalizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacionField, value) != true)) {
                    this.LocalizacionField = value;
                    this.RaisePropertyChanged("Localizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSodaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoUnitario {
            get {
                return this.CostoUnitarioField;
            }
            set {
                if ((this.CostoUnitarioField.Equals(value) != true)) {
                    this.CostoUnitarioField = value;
                    this.RaisePropertyChanged("CostoUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCarrito {
            get {
                return this.IdCarritoField;
            }
            set {
                if ((this.IdCarritoField.Equals(value) != true)) {
                    this.IdCarritoField = value;
                    this.RaisePropertyChanged("IdCarrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoda {
            get {
                return this.IdSodaField;
            }
            set {
                if ((this.IdSodaField.Equals(value) != true)) {
                    this.IdSodaField = value;
                    this.RaisePropertyChanged("IdSoda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContPersonalizado", Namespace="http://schemas.datacontract.org/2004/07/WebTikiService")]
    [System.SerializableAttribute()]
    public partial class ContPersonalizado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContNombField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentDeProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContNomb {
            get {
                return this.ContNombField;
            }
            set {
                if ((object.ReferenceEquals(this.ContNombField, value) != true)) {
                    this.ContNombField = value;
                    this.RaisePropertyChanged("ContNomb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCarrito {
            get {
                return this.IdCarritoField;
            }
            set {
                if ((this.IdCarritoField.Equals(value) != true)) {
                    this.IdCarritoField = value;
                    this.RaisePropertyChanged("IdCarrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContenido {
            get {
                return this.IdContenidoField;
            }
            set {
                if ((this.IdContenidoField.Equals(value) != true)) {
                    this.IdContenidoField = value;
                    this.RaisePropertyChanged("IdContenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdentDeProduct {
            get {
                return this.IdentDeProductField;
            }
            set {
                if ((this.IdentDeProductField.Equals(value) != true)) {
                    this.IdentDeProductField = value;
                    this.RaisePropertyChanged("IdentDeProduct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarData", ReplyAction="http://tempuri.org/IService1/ConsultarDataResponse")]
        Index.ServiceReference1.Producto[] ConsultarData(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarData", ReplyAction="http://tempuri.org/IService1/ConsultarDataResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Producto[]> ConsultarDataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultContenido", ReplyAction="http://tempuri.org/IService1/ConsultContenidoResponse")]
        Index.ServiceReference1.ContProd[] ConsultContenido(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultContenido", ReplyAction="http://tempuri.org/IService1/ConsultContenidoResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.ContProd[]> ConsultContenidoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultContProd", ReplyAction="http://tempuri.org/IService1/ConsultContProdResponse")]
        string ConsultContProd(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultContProd", ReplyAction="http://tempuri.org/IService1/ConsultContProdResponse")]
        System.Threading.Tasks.Task<string> ConsultContProdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultIdPed", ReplyAction="http://tempuri.org/IService1/ConsultIdPedResponse")]
        int ConsultIdPed(int idCarri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultIdPed", ReplyAction="http://tempuri.org/IService1/ConsultIdPedResponse")]
        System.Threading.Tasks.Task<int> ConsultIdPedAsync(int idCarri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsProduct", ReplyAction="http://tempuri.org/IService1/ConsProductResponse")]
        Index.ServiceReference1.Producto[] ConsProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsProduct", ReplyAction="http://tempuri.org/IService1/ConsProductResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Producto[]> ConsProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InfoSoda", ReplyAction="http://tempuri.org/IService1/InfoSodaResponse")]
        Index.ServiceReference1.Soda[] InfoSoda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InfoSoda", ReplyAction="http://tempuri.org/IService1/InfoSodaResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Soda[]> InfoSodaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        Index.ServiceReference1.Usuario[] Login(int IdUsuario, string Contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> LoginAsync(int IdUsuario, string Contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMutlProdPers", ReplyAction="http://tempuri.org/IService1/ObtenerMutlProdPersResponse")]
        int ObtenerMutlProdPers(int shopC, int ped, int idProd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMutlProdPers", ReplyAction="http://tempuri.org/IService1/ObtenerMutlProdPersResponse")]
        System.Threading.Tasks.Task<int> ObtenerMutlProdPersAsync(int shopC, int ped, int idProd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarios", ReplyAction="http://tempuri.org/IService1/ObtenerUsuariosResponse")]
        Index.ServiceReference1.Usuario[] ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarios", ReplyAction="http://tempuri.org/IService1/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAdministradorContrasenia", ReplyAction="http://tempuri.org/IService1/ObtenerAdministradorContraseniaResponse")]
        Index.ServiceReference1.Administrador[] ObtenerAdministradorContrasenia(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAdministradorContrasenia", ReplyAction="http://tempuri.org/IService1/ObtenerAdministradorContraseniaResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Administrador[]> ObtenerAdministradorContraseniaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarioContrasenia", ReplyAction="http://tempuri.org/IService1/ObtenerUsuarioContraseniaResponse")]
        Index.ServiceReference1.Usuario[] ObtenerUsuarioContrasenia(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerUsuarioContrasenia", ReplyAction="http://tempuri.org/IService1/ObtenerUsuarioContraseniaResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> ObtenerUsuarioContraseniaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPedido", ReplyAction="http://tempuri.org/IService1/ObtenerPedidoResponse")]
        Index.ServiceReference1.Pedido[] ObtenerPedido(int ped, int carrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPedido", ReplyAction="http://tempuri.org/IService1/ObtenerPedidoResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Pedido[]> ObtenerPedidoAsync(int ped, int carrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProductoPer", ReplyAction="http://tempuri.org/IService1/ObtenerProductoPerResponse")]
        Index.ServiceReference1.ContPersonalizado[] ObtenerProductoPer(int shopC, int ped, int idProd, int iden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProductoPer", ReplyAction="http://tempuri.org/IService1/ObtenerProductoPerResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.ContPersonalizado[]> ObtenerProductoPerAsync(int shopC, int ped, int idProd, int iden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProductoPer", ReplyAction="http://tempuri.org/IService1/EditProductoPerResponse")]
        Index.ServiceReference1.ContPersonalizado[] EditProductoPer(int carrito, int ped, int idProd, int identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditProductoPer", ReplyAction="http://tempuri.org/IService1/EditProductoPerResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.ContPersonalizado[]> EditProductoPerAsync(int carrito, int ped, int idProd, int identidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPedido", ReplyAction="http://tempuri.org/IService1/AgregarPedidoResponse")]
        void AgregarPedido(int idPedido, int idCarrito, int idProducto, int cantidad, decimal costounitario, decimal costoTotal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarPedido", ReplyAction="http://tempuri.org/IService1/AgregarPedidoResponse")]
        System.Threading.Tasks.Task AgregarPedidoAsync(int idPedido, int idCarrito, int idProducto, int cantidad, decimal costounitario, decimal costoTotal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPedido", ReplyAction="http://tempuri.org/IService1/EliminarPedidoResponse")]
        void EliminarPedido(string nombre, int pedido, int carrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPedido", ReplyAction="http://tempuri.org/IService1/EliminarPedidoResponse")]
        System.Threading.Tasks.Task EliminarPedidoAsync(string nombre, int pedido, int carrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarContPers", ReplyAction="http://tempuri.org/IService1/AgregarContPersResponse")]
        void AgregarContPers(int idProd, int inde, int idCont, string ContNomb, int idCarr, int idPed, int cant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarContPers", ReplyAction="http://tempuri.org/IService1/AgregarContPersResponse")]
        System.Threading.Tasks.Task AgregarContPersAsync(int idProd, int inde, int idCont, string ContNomb, int idCarr, int idPed, int cant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarCantidad", ReplyAction="http://tempuri.org/IService1/ModificarCantidadResponse")]
        void ModificarCantidad(int idPedido, int carrito, int cantidad, int identi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarCantidad", ReplyAction="http://tempuri.org/IService1/ModificarCantidadResponse")]
        System.Threading.Tasks.Task ModificarCantidadAsync(int idPedido, int carrito, int cantidad, int identi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        void AgregarCliente(int idUsuario, string nombre, string apellido, string correo, string contraseña, string telefono, string localizacion, int idcarrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        System.Threading.Tasks.Task AgregarClienteAsync(int idUsuario, string nombre, string apellido, string correo, string contraseña, string telefono, string localizacion, int idcarrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPedidoPorIDSoda", ReplyAction="http://tempuri.org/IService1/ObtenerPedidoPorIDSodaResponse")]
        Index.ServiceReference1.Pedido[] ObtenerPedidoPorIDSoda(int idsoda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerPedidoPorIDSoda", ReplyAction="http://tempuri.org/IService1/ObtenerPedidoPorIDSodaResponse")]
        System.Threading.Tasks.Task<Index.ServiceReference1.Pedido[]> ObtenerPedidoPorIDSodaAsync(int idsoda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCarrito", ReplyAction="http://tempuri.org/IService1/AgregarCarritoResponse")]
        void AgregarCarrito(int carrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCarrito", ReplyAction="http://tempuri.org/IService1/AgregarCarritoResponse")]
        System.Threading.Tasks.Task AgregarCarritoAsync(int carrito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Index.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Index.ServiceReference1.IService1>, Index.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Index.ServiceReference1.Producto[] ConsultarData(int id) {
            return base.Channel.ConsultarData(id);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Producto[]> ConsultarDataAsync(int id) {
            return base.Channel.ConsultarDataAsync(id);
        }
        
        public Index.ServiceReference1.ContProd[] ConsultContenido(int id) {
            return base.Channel.ConsultContenido(id);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.ContProd[]> ConsultContenidoAsync(int id) {
            return base.Channel.ConsultContenidoAsync(id);
        }
        
        public string ConsultContProd(int id) {
            return base.Channel.ConsultContProd(id);
        }
        
        public System.Threading.Tasks.Task<string> ConsultContProdAsync(int id) {
            return base.Channel.ConsultContProdAsync(id);
        }
        
        public int ConsultIdPed(int idCarri) {
            return base.Channel.ConsultIdPed(idCarri);
        }
        
        public System.Threading.Tasks.Task<int> ConsultIdPedAsync(int idCarri) {
            return base.Channel.ConsultIdPedAsync(idCarri);
        }
        
        public Index.ServiceReference1.Producto[] ConsProduct() {
            return base.Channel.ConsProduct();
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Producto[]> ConsProductAsync() {
            return base.Channel.ConsProductAsync();
        }
        
        public Index.ServiceReference1.Soda[] InfoSoda() {
            return base.Channel.InfoSoda();
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Soda[]> InfoSodaAsync() {
            return base.Channel.InfoSodaAsync();
        }
        
        public Index.ServiceReference1.Usuario[] Login(int IdUsuario, string Contraseña) {
            return base.Channel.Login(IdUsuario, Contraseña);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> LoginAsync(int IdUsuario, string Contraseña) {
            return base.Channel.LoginAsync(IdUsuario, Contraseña);
        }
        
        public int ObtenerMutlProdPers(int shopC, int ped, int idProd) {
            return base.Channel.ObtenerMutlProdPers(shopC, ped, idProd);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerMutlProdPersAsync(int shopC, int ped, int idProd) {
            return base.Channel.ObtenerMutlProdPersAsync(shopC, ped, idProd);
        }
        
        public Index.ServiceReference1.Usuario[] ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public Index.ServiceReference1.Administrador[] ObtenerAdministradorContrasenia(string cedula) {
            return base.Channel.ObtenerAdministradorContrasenia(cedula);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Administrador[]> ObtenerAdministradorContraseniaAsync(string cedula) {
            return base.Channel.ObtenerAdministradorContraseniaAsync(cedula);
        }
        
        public Index.ServiceReference1.Usuario[] ObtenerUsuarioContrasenia(string cedula) {
            return base.Channel.ObtenerUsuarioContrasenia(cedula);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Usuario[]> ObtenerUsuarioContraseniaAsync(string cedula) {
            return base.Channel.ObtenerUsuarioContraseniaAsync(cedula);
        }
        
        public Index.ServiceReference1.Pedido[] ObtenerPedido(int ped, int carrito) {
            return base.Channel.ObtenerPedido(ped, carrito);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Pedido[]> ObtenerPedidoAsync(int ped, int carrito) {
            return base.Channel.ObtenerPedidoAsync(ped, carrito);
        }
        
        public Index.ServiceReference1.ContPersonalizado[] ObtenerProductoPer(int shopC, int ped, int idProd, int iden) {
            return base.Channel.ObtenerProductoPer(shopC, ped, idProd, iden);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.ContPersonalizado[]> ObtenerProductoPerAsync(int shopC, int ped, int idProd, int iden) {
            return base.Channel.ObtenerProductoPerAsync(shopC, ped, idProd, iden);
        }
        
        public Index.ServiceReference1.ContPersonalizado[] EditProductoPer(int carrito, int ped, int idProd, int identidad) {
            return base.Channel.EditProductoPer(carrito, ped, idProd, identidad);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.ContPersonalizado[]> EditProductoPerAsync(int carrito, int ped, int idProd, int identidad) {
            return base.Channel.EditProductoPerAsync(carrito, ped, idProd, identidad);
        }
        
        public void AgregarPedido(int idPedido, int idCarrito, int idProducto, int cantidad, decimal costounitario, decimal costoTotal) {
            base.Channel.AgregarPedido(idPedido, idCarrito, idProducto, cantidad, costounitario, costoTotal);
        }
        
        public System.Threading.Tasks.Task AgregarPedidoAsync(int idPedido, int idCarrito, int idProducto, int cantidad, decimal costounitario, decimal costoTotal) {
            return base.Channel.AgregarPedidoAsync(idPedido, idCarrito, idProducto, cantidad, costounitario, costoTotal);
        }
        
        public void EliminarPedido(string nombre, int pedido, int carrito) {
            base.Channel.EliminarPedido(nombre, pedido, carrito);
        }
        
        public System.Threading.Tasks.Task EliminarPedidoAsync(string nombre, int pedido, int carrito) {
            return base.Channel.EliminarPedidoAsync(nombre, pedido, carrito);
        }
        
        public void AgregarContPers(int idProd, int inde, int idCont, string ContNomb, int idCarr, int idPed, int cant) {
            base.Channel.AgregarContPers(idProd, inde, idCont, ContNomb, idCarr, idPed, cant);
        }
        
        public System.Threading.Tasks.Task AgregarContPersAsync(int idProd, int inde, int idCont, string ContNomb, int idCarr, int idPed, int cant) {
            return base.Channel.AgregarContPersAsync(idProd, inde, idCont, ContNomb, idCarr, idPed, cant);
        }
        
        public void ModificarCantidad(int idPedido, int carrito, int cantidad, int identi) {
            base.Channel.ModificarCantidad(idPedido, carrito, cantidad, identi);
        }
        
        public System.Threading.Tasks.Task ModificarCantidadAsync(int idPedido, int carrito, int cantidad, int identi) {
            return base.Channel.ModificarCantidadAsync(idPedido, carrito, cantidad, identi);
        }
        
        public void AgregarCliente(int idUsuario, string nombre, string apellido, string correo, string contraseña, string telefono, string localizacion, int idcarrito) {
            base.Channel.AgregarCliente(idUsuario, nombre, apellido, correo, contraseña, telefono, localizacion, idcarrito);
        }
        
        public System.Threading.Tasks.Task AgregarClienteAsync(int idUsuario, string nombre, string apellido, string correo, string contraseña, string telefono, string localizacion, int idcarrito) {
            return base.Channel.AgregarClienteAsync(idUsuario, nombre, apellido, correo, contraseña, telefono, localizacion, idcarrito);
        }
        
        public Index.ServiceReference1.Pedido[] ObtenerPedidoPorIDSoda(int idsoda) {
            return base.Channel.ObtenerPedidoPorIDSoda(idsoda);
        }
        
        public System.Threading.Tasks.Task<Index.ServiceReference1.Pedido[]> ObtenerPedidoPorIDSodaAsync(int idsoda) {
            return base.Channel.ObtenerPedidoPorIDSodaAsync(idsoda);
        }
        
        public void AgregarCarrito(int carrito) {
            base.Channel.AgregarCarrito(carrito);
        }
        
        public System.Threading.Tasks.Task AgregarCarritoAsync(int carrito) {
            return base.Channel.AgregarCarritoAsync(carrito);
        }
    }
}
