//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.WcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Datos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maritalstatus {
            get {
                return this.MaritalstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalstatusField, value) != true)) {
                    this.MaritalstatusField = value;
                    this.RaisePropertyChanged("Maritalstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.birthDateField, value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobTitleField, value) != true)) {
                    this.jobTitleField = value;
                    this.RaisePropertyChanged("jobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginID {
            get {
                return this.loginIDField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIDField, value) != true)) {
                    this.loginIDField = value;
                    this.RaisePropertyChanged("loginID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IIDatos")]
    public interface IIDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDatos/consultarData", ReplyAction="http://tempuri.org/IIDatos/consultarDataResponse")]
        WebClient.WcfServiceReference.Datos consultarData(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDatos/consultarData", ReplyAction="http://tempuri.org/IIDatos/consultarDataResponse")]
        System.Threading.Tasks.Task<WebClient.WcfServiceReference.Datos> consultarDataAsync(string ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIDatosChannel : WebClient.WcfServiceReference.IIDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IDatosClient : System.ServiceModel.ClientBase<WebClient.WcfServiceReference.IIDatos>, WebClient.WcfServiceReference.IIDatos {
        
        public IDatosClient() {
        }
        
        public IDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebClient.WcfServiceReference.Datos consultarData(string ID) {
            return base.Channel.consultarData(ID);
        }
        
        public System.Threading.Tasks.Task<WebClient.WcfServiceReference.Datos> consultarDataAsync(string ID) {
            return base.Channel.consultarDataAsync(ID);
        }
    }
}
